var content = '<header style="box-shadow: 0px 0px 15px 0px #000000;">'
+'<div class="container p-2">'
+'<div class="row justify-content-center align-items-center">'
+'<div class="col-sm-2 text-center"><img class="img-fluid" src="img/logo.png" alt=""></div>'
+'<ul style="list-style: none;" class="col-sm-10 d-flex justify-content-end align-items-center text-end">'
+'<li class="mx-2">Home</li>'
+'<li class="mx-2"><a style="text-decoration: none;" href="./aluno.html" >Aluno</a></li>'
+'<li class="mx-2"><a style="text-decoration: none;" href="./professor.html" >Professor</a></li>'
+'<li class="mx-2"><a style="text-decoration: none;" href="./materia.html" >Matéria</a></li>'
+'<li class="mx-2"><a style="text-decoration: none;" href="./curso.html" >Curso</a></li>'
+'<li class="mx-2"><a style="text-decoration: none;" href="./grade.html" >Grade</a></li>'
+'</ul>'
+'</div>'
+'</div>'
+'</header>'
document.getElementById("header").innerHTML = content
